#!/usr/bin/env bash

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BOOTSTRAP_FILE="$HOME/.para-llm-root"

# Parse flags
NON_INTERACTIVE=false
for arg in "$@"; do
    case "$arg" in
        -y|--yes) NON_INTERACTIVE=true ;;
    esac
done

detect_package_manager() {
    if command -v brew &>/dev/null; then echo "brew"
    elif command -v apt-get &>/dev/null; then echo "apt"
    elif command -v dnf &>/dev/null; then echo "dnf"
    elif command -v pacman &>/dev/null; then echo "pacman"
    elif command -v apk &>/dev/null; then echo "apk"
    else echo "unknown"
    fi
}

pkg_install() {
    local pkg="$1"
    case "$(detect_package_manager)" in
        brew)   brew install "$pkg" ;;
        apt)    sudo apt-get install -y "$pkg" ;;
        dnf)    sudo dnf install -y "$pkg" ;;
        pacman) sudo pacman -S --noconfirm "$pkg" ;;
        apk)    sudo apk add "$pkg" ;;
        *)      echo "Unknown package manager. Please install '$pkg' manually." >&2; return 1 ;;
    esac
}

echo "Installing para-llm-directory..."
echo ""

# Check for existing config via bootstrap pointer
if [[ -f "$BOOTSTRAP_FILE" ]]; then
    EXISTING_ROOT="$(cat "$BOOTSTRAP_FILE")"
    if [[ -f "$EXISTING_ROOT/config" ]]; then
        source "$EXISTING_ROOT/config"
        PARA_LLM_ROOT="$EXISTING_ROOT"
        echo "Found existing configuration:"
        echo "  Base repos directory: $CODE_DIR"
        echo "  Para-LLM root: $PARA_LLM_ROOT"
        echo ""
        if [[ "$NON_INTERACTIVE" == true ]]; then
            echo "Keeping existing settings (-y)"
        else
            read -r -p "Keep existing settings? [Y/n]: " KEEP_CONFIG
            if [[ "$KEEP_CONFIG" =~ ^[Nn] ]]; then
                unset CODE_DIR PARA_LLM_ROOT
            fi
        fi
        echo ""
    fi
fi

# Prompt for directories if not already set
if [[ -z "$CODE_DIR" ]]; then
    DEFAULT_CODE_DIR="$(pwd)"
    if [[ "$NON_INTERACTIVE" == true ]]; then
        CODE_DIR="$DEFAULT_CODE_DIR"
        echo "Using default base repos directory: $CODE_DIR"
    else
        echo "Where are your base git repositories located?"
        echo "(Default is the current directory)"
        echo ""
        read -r -p "Base repos directory [$DEFAULT_CODE_DIR]: " CODE_DIR
        CODE_DIR="${CODE_DIR:-$DEFAULT_CODE_DIR}"
        # Expand ~ to $HOME
        CODE_DIR="${CODE_DIR/#\~/$HOME}"
    fi
    echo ""
fi

if [[ -z "$PARA_LLM_ROOT" ]]; then
    DEFAULT_PARA_LLM_ROOT="$CODE_DIR/.para-llm-directory"
    if [[ "$NON_INTERACTIVE" == true ]]; then
        PARA_LLM_ROOT="$DEFAULT_PARA_LLM_ROOT"
        echo "Using default para-llm root: $PARA_LLM_ROOT"
    else
        echo "Where should para-llm-directory store its data?"
        echo "(Environments, recovery state, and plugins live here)"
        echo ""
        read -r -p "Para-LLM root [$DEFAULT_PARA_LLM_ROOT]: " PARA_LLM_ROOT
        PARA_LLM_ROOT="${PARA_LLM_ROOT:-$DEFAULT_PARA_LLM_ROOT}"
        # Expand ~ to $HOME
        PARA_LLM_ROOT="${PARA_LLM_ROOT/#\~/$HOME}"
    fi
    echo ""
fi

# Derive ENVS_DIR
ENVS_DIR="$PARA_LLM_ROOT/envs"

CLAUDE_LAUNCH_ARGS="${CLAUDE_LAUNCH_ARGS:---permission-mode auto}"
CODEX_LAUNCH_ARGS="${CODEX_LAUNCH_ARGS:-}"
PARA_LLM_DEFAULT_REPL="${PARA_LLM_DEFAULT_REPL:-claude}"
echo ""

# Create directory structure
mkdir -p "$PARA_LLM_ROOT"
mkdir -p "$ENVS_DIR"
mkdir -p "$PARA_LLM_ROOT/recovery"
mkdir -p "$PARA_LLM_ROOT/recovery/pane-display"
mkdir -p "$PARA_LLM_ROOT/scripts"
mkdir -p "$PARA_LLM_ROOT/tmux-plugins"
mkdir -p "$PARA_LLM_ROOT/plugins"
mkdir -p "$PARA_LLM_ROOT/remotes"

# Write bootstrap pointer
echo "$PARA_LLM_ROOT" > "$BOOTSTRAP_FILE"

# Save configuration to PARA_LLM_ROOT/config
cat > "$PARA_LLM_ROOT/config" << 'EOF'
# para-llm-directory configuration
# Generated by install.sh

EOF
# Add config values with actual expansion (heredoc is single-quoted so vars don't expand)
echo "# Directory containing your base git repositories" >> "$PARA_LLM_ROOT/config"
echo "CODE_DIR=\"$CODE_DIR\"" >> "$PARA_LLM_ROOT/config"
echo "" >> "$PARA_LLM_ROOT/config"
echo "# Directory where para-llm-directory is installed (source scripts)" >> "$PARA_LLM_ROOT/config"
echo "INSTALL_DIR=\"$SCRIPT_DIR\"" >> "$PARA_LLM_ROOT/config"
echo "" >> "$PARA_LLM_ROOT/config"
echo "# REPL launch profiles and default per-env REPL" >> "$PARA_LLM_ROOT/config"
echo "PARA_LLM_DEFAULT_REPL=\"$PARA_LLM_DEFAULT_REPL\"" >> "$PARA_LLM_ROOT/config"
echo "CLAUDE_LAUNCH_ARGS=\"$CLAUDE_LAUNCH_ARGS\"" >> "$PARA_LLM_ROOT/config"
echo "CODEX_LAUNCH_ARGS=\"$CODEX_LAUNCH_ARGS\"" >> "$PARA_LLM_ROOT/config"
cat >> "$PARA_LLM_ROOT/config" << 'EOF'

# tmux status line settings
# Shows aggregate Claude state in tmux status bar
STATUS_LINE_ENABLED=1
STATUS_LINE_EMOJI=0
# STATUS_LINE_PREFIX="Claude"
EOF

# --- Always-on voice layer ---
echo ""
echo "Setting up voice input/output..."
echo "  STT: Ctrl+b a records and transcribes with whisper.cpp"
echo "  TTS: Ctrl+b p speaks/stops latest pane output with Microsoft edge-tts"

# Check/install sox
if ! command -v rec &>/dev/null; then
    echo "  Installing sox (audio recording)..."
    pkg_install sox 2>/dev/null || echo "  Warning: Failed to install sox. Install with your package manager."
else
    echo "  sox already installed"
fi

# Check/install whisper-cpp
if ! command -v whisper-cli &>/dev/null && ! command -v whisper-cpp &>/dev/null; then
    echo "  Installing whisper-cpp (speech recognition)..."
    pkg_install whisper-cpp 2>/dev/null || echo "  Warning: Failed to install whisper-cpp. Install with your package manager."
else
    echo "  whisper-cpp already installed"
fi

echo "  Whisper model (~142 MB) will be auto-downloaded on first use"

if ! command -v edge-tts &>/dev/null; then
    echo "  Warning: edge-tts not found. Install with: pipx install edge-tts"
else
    echo "  edge-tts already installed"
fi

cat >> "$PARA_LLM_ROOT/config" << 'EOF'

# Voice settings
STT_ENABLED=1
TTS_ENABLED=1
TTS_AMBIENT_SOUND_ENABLED=1
TTS_AMBIENT_SOUND_INTERVAL="1"
TTS_AMBIENT_SOUND="/System/Library/Sounds/Tink.aiff"
TTS_AMBIENT_MAX_SECONDS="120"   # Stop the "preparing" beep after this many seconds (0 = no cap)
TTS_VOICE="en-US-AndrewNeural"
TTS_RATE="+0%"
TTS_VOLUME="+0%"
TTS_PITCH="+0Hz"
TTS_SUMMARIZE=1
TTS_SUMMARIZER_BACKEND="codex"   # codex only; claude -p retired (metered, see ADR-009)
TTS_SUMMARIZE_TIMEOUT="60"       # Max seconds for the LLM summarizer before falling back to raw text (0 = no cap)
TTS_SYNTH_TIMEOUT="60"           # Max seconds for edge-tts audio synthesis (0 = no cap)
TTS_PROGRESS_ENABLED=1           # Show live "TTS: <stage> (Ns)" progress in the status line
TTS_PROGRESS_INTERVAL="1"        # How often (seconds) to refresh the progress indicator
TTS_AUTHORED_MAX_AGE="900"       # Seconds an agent-authored voice script (voice-script.sh) stays playable before falling back to live capture (0 = never expires)
# STT_LANGUAGE="en"
# STT_MODEL_PATH=""  # Override model location (default: $PARA_LLM_ROOT/plugins/stt/models/ggml-base.en.bin)
EOF

# Add remote save config
cat >> "$PARA_LLM_ROOT/config" << 'EOF'

# Remote save (push state to remote on each save cycle)
# Disable via Ctrl+b t > Disable automatic updates, or set manually
REMOTE_SAVE_ENABLED=1
EOF

echo "Configuration saved:"
echo "  Bootstrap pointer: $BOOTSTRAP_FILE"
echo "  Config: $PARA_LLM_ROOT/config"
echo "  Base repos: $CODE_DIR"
echo "  Environments: $ENVS_DIR"
echo "  Default REPL: $PARA_LLM_DEFAULT_REPL"
echo ""

# Check for fzf
if ! command -v fzf &> /dev/null; then
    echo "fzf not found. Installing..."
    pkg_install fzf
fi

# Make scripts executable
chmod +x "$SCRIPT_DIR/tmux-new-branch.sh"
chmod +x "$SCRIPT_DIR/tmux-cleanup-branch.sh"
chmod +x "$SCRIPT_DIR/envs.sh"
chmod +x "$SCRIPT_DIR/tmux-command-center.sh"
chmod +x "$SCRIPT_DIR/tmux-cc-hooks.sh"
chmod +x "$SCRIPT_DIR/tmux-repl-selector.sh"
chmod +x "$SCRIPT_DIR/para-llm-config.sh"

# Make plugin scripts executable (including helper scripts)
if [[ -d "$SCRIPT_DIR/plugins/claude-state-monitor" ]]; then
    chmod +x "$SCRIPT_DIR/plugins/claude-state-monitor/"*.sh 2>/dev/null || true
    chmod +x "$SCRIPT_DIR/plugins/claude-state-monitor/hooks/"*.sh 2>/dev/null || true
fi
if [[ -d "$SCRIPT_DIR/plugins/stt" ]]; then
    chmod +x "$SCRIPT_DIR/plugins/stt/"*.sh 2>/dev/null || true
fi
if [[ -d "$SCRIPT_DIR/plugins/tts" ]]; then
    chmod +x "$SCRIPT_DIR/plugins/tts/"*.sh 2>/dev/null || true
fi
if [[ -d "$SCRIPT_DIR/plugins/remote-save" ]]; then
    chmod +x "$SCRIPT_DIR/plugins/remote-save/"*.sh 2>/dev/null || true
    chmod +x "$SCRIPT_DIR/plugins/remote-save/backends/"*.sh 2>/dev/null || true
fi

# --- Agent voice-script skill (Claude Code skill + Codex prompt) ---
# Lets the coding agent author a speakable briefing that Ctrl+b p plays directly,
# skipping capture + LLM summarization. Both files point at the same recorder.
VOICE_SCRIPT_PATH="$SCRIPT_DIR/plugins/tts/voice-script.sh"
SKILL_SRC="$SCRIPT_DIR/plugins/tts/agent-skill"
if [[ -f "$SKILL_SRC/SKILL.md" ]]; then
    CLAUDE_SKILL_DIR="$HOME/.claude/skills/para-voice-script"
    mkdir -p "$CLAUDE_SKILL_DIR"
    sed "s|__VOICE_SCRIPT_PATH__|$VOICE_SCRIPT_PATH|g" "$SKILL_SRC/SKILL.md" > "$CLAUDE_SKILL_DIR/SKILL.md"
    echo "  Installed Claude Code skill: para-voice-script"
fi
if [[ -f "$SKILL_SRC/codex-prompt.md" ]]; then
    CODEX_PROMPT_DIR="$HOME/.codex/prompts"
    mkdir -p "$CODEX_PROMPT_DIR"
    sed "s|__VOICE_SCRIPT_PATH__|$VOICE_SCRIPT_PATH|g" "$SKILL_SRC/codex-prompt.md" > "$CODEX_PROMPT_DIR/voice-script.md"
    echo "  Installed Codex prompt: /voice-script"
fi

# Make recovery scripts executable
chmod +x "$SCRIPT_DIR/scripts/"*.sh 2>/dev/null || true

# Copy recovery scripts to PARA_LLM_ROOT
echo "Installing recovery scripts..."
cp "$SCRIPT_DIR/scripts/para-llm-save-state.sh" "$PARA_LLM_ROOT/scripts/"
cp "$SCRIPT_DIR/scripts/para-llm-restore.sh" "$PARA_LLM_ROOT/scripts/"
cp "$SCRIPT_DIR/scripts/para-llm-recovery-prompt.sh" "$PARA_LLM_ROOT/scripts/"
cp "$SCRIPT_DIR/scripts/para-llm-do-restore.sh" "$PARA_LLM_ROOT/scripts/"
cp "$SCRIPT_DIR/scripts/para-llm-do-discard.sh" "$PARA_LLM_ROOT/scripts/"
cp "$SCRIPT_DIR/scripts/para-llm-upgrade-envs.sh" "$PARA_LLM_ROOT/scripts/"
cp "$SCRIPT_DIR/para-llm-config.sh" "$PARA_LLM_ROOT/scripts/"
# Clean up stale scripts that should not be in $PARA_LLM_ROOT/scripts/
rm -f "$PARA_LLM_ROOT/scripts/tmux-command-center.sh"
chmod +x "$PARA_LLM_ROOT/scripts/"*.sh
echo "  Installed recovery scripts to $PARA_LLM_ROOT/scripts/"

# Install tmux-resurrect and tmux-continuum
echo ""
echo "Installing tmux plugins..."

RESURRECT_DIR="$PARA_LLM_ROOT/tmux-plugins/tmux-resurrect"
CONTINUUM_DIR="$PARA_LLM_ROOT/tmux-plugins/tmux-continuum"

if [[ -d "$RESURRECT_DIR" ]]; then
    echo "  tmux-resurrect already installed, updating..."
    git -C "$RESURRECT_DIR" pull --quiet 2>/dev/null || true
else
    echo "  Cloning tmux-resurrect..."
    git clone --quiet https://github.com/tmux-plugins/tmux-resurrect.git "$RESURRECT_DIR"
fi

if [[ -d "$CONTINUUM_DIR" ]]; then
    echo "  tmux-continuum already installed, updating..."
    git -C "$CONTINUUM_DIR" pull --quiet 2>/dev/null || true
else
    echo "  Cloning tmux-continuum..."
    git clone --quiet https://github.com/tmux-plugins/tmux-continuum.git "$CONTINUUM_DIR"
fi

echo "  Plugins installed to $PARA_LLM_ROOT/tmux-plugins/"

# Install Claude Code hooks for state monitoring
echo ""
echo "Setting up Claude Code hooks for state monitoring..."

# Create hooks directory in PARA_LLM_ROOT
HOOKS_INSTALL_DIR="$PARA_LLM_ROOT/plugins/claude-state-monitor/hooks"
mkdir -p "$HOOKS_INSTALL_DIR"

# Copy state-tracker script
cp "$SCRIPT_DIR/plugins/claude-state-monitor/hooks/state-tracker.sh" "$HOOKS_INSTALL_DIR/"
chmod +x "$HOOKS_INSTALL_DIR/state-tracker.sh"
echo "  Installed state-tracker.sh to $HOOKS_INSTALL_DIR"

# Merge hooks configuration into Claude settings
CLAUDE_SETTINGS="$HOME/.claude/settings.json"
HOOKS_CONFIG="$SCRIPT_DIR/plugins/claude-state-monitor/hooks/hooks-config.json"

if [[ -f "$HOOKS_CONFIG" ]]; then
    mkdir -p "$HOME/.claude"

    if [[ -f "$CLAUDE_SETTINGS" ]]; then
        # Backup existing settings
        cp "$CLAUDE_SETTINGS" "$CLAUDE_SETTINGS.backup"
        echo "  Backed up $CLAUDE_SETTINGS"

        # Check if jq is available
        if command -v jq &> /dev/null; then
            # Merge hooks into existing settings, substituting PARA_LLM_ROOT path
            NEW_HOOKS=$(sed "s|__PARA_LLM_ROOT__|$PARA_LLM_ROOT|g" "$HOOKS_CONFIG" | jq '.hooks')

            # Merge and write back
            jq --argjson new "$NEW_HOOKS" '.hooks = (.hooks // {}) + $new' "$CLAUDE_SETTINGS" > "$CLAUDE_SETTINGS.tmp" && \
                mv "$CLAUDE_SETTINGS.tmp" "$CLAUDE_SETTINGS"
            echo "  Merged hooks configuration into $CLAUDE_SETTINGS"
        else
            echo "  Warning: jq not found, cannot merge hooks automatically"
            echo "  Please manually add hooks from: $HOOKS_CONFIG"
            echo "  to your: $CLAUDE_SETTINGS"
        fi
    else
        # No existing settings, create with substituted paths
        sed "s|__PARA_LLM_ROOT__|$PARA_LLM_ROOT|g" "$HOOKS_CONFIG" > "$CLAUDE_SETTINGS"
        echo "  Created $CLAUDE_SETTINGS with hooks configuration"
    fi
fi

# Backup existing tmux.conf if it exists
echo ""
if [[ -f ~/.tmux.conf ]]; then
    cp ~/.tmux.conf ~/.tmux.conf.backup
    echo "Backed up existing ~/.tmux.conf to ~/.tmux.conf.backup"
fi

# Remove existing para-llm-directory bindings if present
if grep -q "para-llm-directory" ~/.tmux.conf 2>/dev/null; then
    echo "Removing existing para-llm-directory bindings..."
    # Remove the block from "# para-llm-directory" to end of our managed section
    sed -i.tmp '/# para-llm-directory bindings/,/# end para-llm-directory/d' ~/.tmux.conf
    rm -f ~/.tmux.conf.tmp
    # Also remove old-style block (before we added end marker)
    if grep -q "para-llm-directory" ~/.tmux.conf 2>/dev/null; then
        sed -i.tmp '/# para-llm-directory/,/synchronize-panes/d' ~/.tmux.conf
        rm -f ~/.tmux.conf.tmp
    fi
    # Clean up any trailing blank lines
    sed -i.tmp -e :a -e '/^\n*$/{$d;N;ba' -e '}' ~/.tmux.conf 2>/dev/null || true
    rm -f ~/.tmux.conf.tmp
fi

# Add bindings to tmux.conf (always fresh)
echo "Adding bindings pointing to: $SCRIPT_DIR"
cat >> ~/.tmux.conf << EOF

# para-llm-directory bindings

# Enable extended keys so Shift+Enter passes through to Claude Code as newline
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

# Enable mouse/trackpad scrolling and pane selection
set -g mouse on

# Copy text: Option+drag to select, then Cmd+C to copy (iTerm2 native selection)

# Ctrl+b c: interactive project + branch selection, creates clone in envs/
bind-key c display-popup -E -w 60% -h 60% "$SCRIPT_DIR/tmux-new-branch.sh"

# Ctrl+b k: cleanup/delete a feature branch environment
bind-key k display-popup -E -w 60% -h 60% "$SCRIPT_DIR/tmux-cleanup-branch.sh"

# Ctrl+b v: Command Center (tiled view of all env windows)
bind-key v run-shell "$SCRIPT_DIR/tmux-command-center.sh"

# Ctrl+b b: Toggle broadcast mode (type in all panes at once)
bind-key b set-window-option synchronize-panes \; display-message "Toggled broadcast mode"

# Ctrl+b t: Remote management menu (add/remove/test/toggle remotes)
bind-key t display-popup -E -w 60% -h 60% "$SCRIPT_DIR/plugins/remote-save/remote-manage.sh"

# Ctrl+b y: choose/switch Claude Code or Codex for the active worktree
bind-key y display-popup -E -w 60% -h 50% "$SCRIPT_DIR/tmux-repl-selector.sh '#{pane_id}' '#{pane_current_path}'"

# Ctrl+b a: Toggle speech-to-text recording (press to record, press again to transcribe)
bind-key a run-shell -b "$SCRIPT_DIR/plugins/stt/toggle-stt.sh"

# Ctrl+b p: Toggle text-to-speech playback for the active pane
bind-key p run-shell -b "$SCRIPT_DIR/plugins/tts/toggle-tts.sh"
EOF

cat >> ~/.tmux.conf << EOF

# para-llm-directory: session recovery
set -g @resurrect-dir '$PARA_LLM_ROOT/recovery/resurrect'
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-hook-post-save-all '$PARA_LLM_ROOT/scripts/para-llm-save-state.sh'
set -g @continuum-restore 'off'
set -g @continuum-save-interval '1'
run-shell $PARA_LLM_ROOT/tmux-plugins/tmux-resurrect/resurrect.tmux
run-shell $PARA_LLM_ROOT/tmux-plugins/tmux-continuum/continuum.tmux

# Recovery prompt on tmux start
set-hook -g session-created 'run-shell -b "sleep 1 && $PARA_LLM_ROOT/scripts/para-llm-recovery-prompt.sh"'

# Ctrl+b r: Manual restore (local sessions)
bind-key r run-shell '$PARA_LLM_ROOT/scripts/para-llm-restore.sh'

# Claude Code status in status line (shows aggregate state)
# Appends to existing status-right, preserving user customizations
set -ga status-right ' #($SCRIPT_DIR/plugins/claude-state-monitor/tmux-status.sh)'
EOF

cat >> ~/.tmux.conf << EOF
set -g status-interval 5
set -g status-right-length 120

# Pane border titles (shows Claude state per pane)
set -g pane-border-status top
set -g pane-border-format '#{?pane_active,#[reverse],} #{window_index}: #{@pane_display} #{?pane_active,#[noreverse],}'
# end para-llm-directory
EOF
echo "Added bindings to ~/.tmux.conf"

# Kill any running state-detector processes (they'll restart with new code when command center reopens)
if pgrep -f "state-detector.sh" >/dev/null 2>&1; then
    pkill -f "state-detector.sh" 2>/dev/null || true
    echo "Stopped old state-detector processes (restart command center to pick up new code)"
fi

# Reload tmux config if tmux is running
if tmux list-sessions &> /dev/null; then
    tmux source-file ~/.tmux.conf
    echo "Reloaded tmux config - bindings updated in place"
fi

echo ""
echo "Installation complete!"
echo ""
echo "Directory structure:"
echo "  $PARA_LLM_ROOT/"
echo "    envs/          - Feature branch environments"
echo "    recovery/      - Session state + resurrect saves"
echo "    scripts/       - Recovery scripts"
echo "    tmux-plugins/  - tmux-resurrect + tmux-continuum"
echo "    plugins/       - Claude state monitor hooks, remote save"
echo "    remotes/       - Remote save backend configs"
echo ""
echo "Keybindings:"
echo "  Ctrl+b c  - Create/resume feature branch"
echo "  Ctrl+b k  - Cleanup feature branch"
echo "  Ctrl+b v  - Command Center (tiled view of all envs)"
echo "  Ctrl+b b  - Toggle broadcast mode (type in all panes)"
echo "  Ctrl+b t  - Remote management (add/test/toggle remotes)"
echo "  Ctrl+b y  - Choose/switch Claude Code or Codex for active worktree"
echo "  Ctrl+b a  - Voice input: record/transcribe into active pane"
echo "  Ctrl+b p  - Voice playback: speak/stop latest pane output"
echo "  Ctrl+b r  - Manual restore managed AI terminal sessions"
echo ""
echo "Recovery:"
echo "  Sessions auto-saved every 1 minute via tmux-continuum"
echo "  On tmux start: prompted to restore/discard/skip"
echo ""
echo "Optional: Add this alias to your ~/.zshrc or ~/.bashrc:"
echo "  alias envs='$SCRIPT_DIR/envs.sh'"
