#!/usr/bin/env bash

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BOOTSTRAP_FILE="$HOME/.para-llm-root"

echo "Installing para-llm-directory..."
echo ""

# Check for existing config via bootstrap pointer
if [[ -f "$BOOTSTRAP_FILE" ]]; then
    EXISTING_ROOT="$(cat "$BOOTSTRAP_FILE")"
    if [[ -f "$EXISTING_ROOT/config" ]]; then
        source "$EXISTING_ROOT/config"
        PARA_LLM_ROOT="$EXISTING_ROOT"
        echo "Found existing configuration:"
        echo "  Base repos directory: $CODE_DIR"
        echo "  Para-LLM root: $PARA_LLM_ROOT"
        echo ""
        read -r -p "Keep existing settings? [Y/n]: " KEEP_CONFIG
        if [[ "$KEEP_CONFIG" =~ ^[Nn] ]]; then
            unset CODE_DIR PARA_LLM_ROOT
        fi
        echo ""
    fi
fi

# Prompt for directories if not already set
if [[ -z "$CODE_DIR" ]]; then
    echo "Where are your base git repositories located?"
    echo "(This is where you keep your main project checkouts)"
    echo ""
    DEFAULT_CODE_DIR="$HOME/code"
    read -r -p "Base repos directory [$DEFAULT_CODE_DIR]: " CODE_DIR
    CODE_DIR="${CODE_DIR:-$DEFAULT_CODE_DIR}"
    # Expand ~ to $HOME
    CODE_DIR="${CODE_DIR/#\~/$HOME}"
    echo ""
fi

if [[ -z "$PARA_LLM_ROOT" ]]; then
    echo "Where should para-llm-directory store its data?"
    echo "(Environments, recovery state, and plugins live here)"
    echo ""
    DEFAULT_PARA_LLM_ROOT="$CODE_DIR/.para-llm-directory"
    read -r -p "Para-LLM root [$DEFAULT_PARA_LLM_ROOT]: " PARA_LLM_ROOT
    PARA_LLM_ROOT="${PARA_LLM_ROOT:-$DEFAULT_PARA_LLM_ROOT}"
    # Expand ~ to $HOME
    PARA_LLM_ROOT="${PARA_LLM_ROOT/#\~/$HOME}"
    echo ""
fi

# Derive ENVS_DIR
ENVS_DIR="$PARA_LLM_ROOT/envs"

# Create directory structure
mkdir -p "$PARA_LLM_ROOT"
mkdir -p "$ENVS_DIR"
mkdir -p "$PARA_LLM_ROOT/recovery"
mkdir -p "$PARA_LLM_ROOT/recovery/pane-display"
mkdir -p "$PARA_LLM_ROOT/scripts"
mkdir -p "$PARA_LLM_ROOT/tmux-plugins"
mkdir -p "$PARA_LLM_ROOT/plugins"

# Write bootstrap pointer
echo "$PARA_LLM_ROOT" > "$BOOTSTRAP_FILE"

# Save configuration to PARA_LLM_ROOT/config
cat > "$PARA_LLM_ROOT/config" << 'EOF'
# para-llm-directory configuration
# Generated by install.sh

EOF
# Add CODE_DIR with actual value (not quoted)
echo "# Directory containing your base git repositories" >> "$PARA_LLM_ROOT/config"
echo "CODE_DIR=\"$CODE_DIR\"" >> "$PARA_LLM_ROOT/config"
cat >> "$PARA_LLM_ROOT/config" << 'EOF'

# Notification settings
# Sound notifications when Claude finishes or needs attention
NOTIFICATION_SOUND_ENABLED=1
NOTIFICATION_SOUND_ONLY_UNFOCUSED=1
# NOTIFICATION_SOUND_IDLE="/System/Library/Sounds/Glass.aiff"
# NOTIFICATION_SOUND_PERMISSION="/System/Library/Sounds/Sosumi.aiff"
EOF

echo "Configuration saved:"
echo "  Bootstrap pointer: $BOOTSTRAP_FILE"
echo "  Config: $PARA_LLM_ROOT/config"
echo "  Base repos: $CODE_DIR"
echo "  Environments: $ENVS_DIR"
echo ""

# Check for fzf
if ! command -v fzf &> /dev/null; then
    echo "fzf not found. Installing via homebrew..."
    brew install fzf
fi

# Make scripts executable
chmod +x "$SCRIPT_DIR/tmux-new-branch.sh"
chmod +x "$SCRIPT_DIR/tmux-cleanup-branch.sh"
chmod +x "$SCRIPT_DIR/envs.sh"
chmod +x "$SCRIPT_DIR/tmux-command-center.sh"
chmod +x "$SCRIPT_DIR/tmux-cc-hooks.sh"
chmod +x "$SCRIPT_DIR/para-llm-config.sh"

# Make plugin scripts executable (including helper scripts)
if [[ -d "$SCRIPT_DIR/plugins/claude-state-monitor" ]]; then
    chmod +x "$SCRIPT_DIR/plugins/claude-state-monitor/"*.sh 2>/dev/null || true
    chmod +x "$SCRIPT_DIR/plugins/claude-state-monitor/hooks/"*.sh 2>/dev/null || true
fi

# Make recovery scripts executable
chmod +x "$SCRIPT_DIR/scripts/"*.sh 2>/dev/null || true

# Copy recovery scripts to PARA_LLM_ROOT
echo "Installing recovery scripts..."
cp "$SCRIPT_DIR/scripts/para-llm-save-state.sh" "$PARA_LLM_ROOT/scripts/"
cp "$SCRIPT_DIR/scripts/para-llm-restore.sh" "$PARA_LLM_ROOT/scripts/"
cp "$SCRIPT_DIR/scripts/para-llm-recovery-prompt.sh" "$PARA_LLM_ROOT/scripts/"
cp "$SCRIPT_DIR/scripts/para-llm-do-restore.sh" "$PARA_LLM_ROOT/scripts/"
cp "$SCRIPT_DIR/scripts/para-llm-do-discard.sh" "$PARA_LLM_ROOT/scripts/"
chmod +x "$PARA_LLM_ROOT/scripts/"*.sh
echo "  Installed recovery scripts to $PARA_LLM_ROOT/scripts/"

# Install tmux-resurrect and tmux-continuum
echo ""
echo "Installing tmux plugins..."

RESURRECT_DIR="$PARA_LLM_ROOT/tmux-plugins/tmux-resurrect"
CONTINUUM_DIR="$PARA_LLM_ROOT/tmux-plugins/tmux-continuum"

if [[ -d "$RESURRECT_DIR" ]]; then
    echo "  tmux-resurrect already installed, updating..."
    git -C "$RESURRECT_DIR" pull --quiet 2>/dev/null || true
else
    echo "  Cloning tmux-resurrect..."
    git clone --quiet https://github.com/tmux-plugins/tmux-resurrect.git "$RESURRECT_DIR"
fi

if [[ -d "$CONTINUUM_DIR" ]]; then
    echo "  tmux-continuum already installed, updating..."
    git -C "$CONTINUUM_DIR" pull --quiet 2>/dev/null || true
else
    echo "  Cloning tmux-continuum..."
    git clone --quiet https://github.com/tmux-plugins/tmux-continuum.git "$CONTINUUM_DIR"
fi

echo "  Plugins installed to $PARA_LLM_ROOT/tmux-plugins/"

# Install Claude Code hooks for state monitoring
echo ""
echo "Setting up Claude Code hooks for state monitoring..."

# Create hooks directory in PARA_LLM_ROOT
HOOKS_INSTALL_DIR="$PARA_LLM_ROOT/plugins/claude-state-monitor/hooks"
mkdir -p "$HOOKS_INSTALL_DIR"

# Copy hook scripts
cp "$SCRIPT_DIR/plugins/claude-state-monitor/hooks/state-tracker.sh" "$HOOKS_INSTALL_DIR/"
cp "$SCRIPT_DIR/plugins/claude-state-monitor/hooks/notification-sound.sh" "$HOOKS_INSTALL_DIR/"
chmod +x "$HOOKS_INSTALL_DIR/state-tracker.sh"
chmod +x "$HOOKS_INSTALL_DIR/notification-sound.sh"
echo "  Installed state-tracker.sh to $HOOKS_INSTALL_DIR"
echo "  Installed notification-sound.sh to $HOOKS_INSTALL_DIR"

# Merge hooks configuration into Claude settings
CLAUDE_SETTINGS="$HOME/.claude/settings.json"
HOOKS_CONFIG="$SCRIPT_DIR/plugins/claude-state-monitor/hooks/hooks-config.json"

if [[ -f "$HOOKS_CONFIG" ]]; then
    mkdir -p "$HOME/.claude"

    if [[ -f "$CLAUDE_SETTINGS" ]]; then
        # Backup existing settings
        cp "$CLAUDE_SETTINGS" "$CLAUDE_SETTINGS.backup"
        echo "  Backed up $CLAUDE_SETTINGS"

        # Check if jq is available
        if command -v jq &> /dev/null; then
            # Merge hooks into existing settings, substituting PARA_LLM_ROOT path
            NEW_HOOKS=$(sed "s|__PARA_LLM_ROOT__|$PARA_LLM_ROOT|g" "$HOOKS_CONFIG" | jq '.hooks')

            # Merge and write back
            jq --argjson new "$NEW_HOOKS" '.hooks = (.hooks // {}) + $new' "$CLAUDE_SETTINGS" > "$CLAUDE_SETTINGS.tmp" && \
                mv "$CLAUDE_SETTINGS.tmp" "$CLAUDE_SETTINGS"
            echo "  Merged hooks configuration into $CLAUDE_SETTINGS"
        else
            echo "  Warning: jq not found, cannot merge hooks automatically"
            echo "  Please manually add hooks from: $HOOKS_CONFIG"
            echo "  to your: $CLAUDE_SETTINGS"
        fi
    else
        # No existing settings, create with substituted paths
        sed "s|__PARA_LLM_ROOT__|$PARA_LLM_ROOT|g" "$HOOKS_CONFIG" > "$CLAUDE_SETTINGS"
        echo "  Created $CLAUDE_SETTINGS with hooks configuration"
    fi
fi

# Backup existing tmux.conf if it exists
echo ""
if [[ -f ~/.tmux.conf ]]; then
    cp ~/.tmux.conf ~/.tmux.conf.backup
    echo "Backed up existing ~/.tmux.conf to ~/.tmux.conf.backup"
fi

# Remove existing para-llm-directory bindings if present
if grep -q "para-llm-directory" ~/.tmux.conf 2>/dev/null; then
    echo "Removing existing para-llm-directory bindings..."
    # Remove the block from "# para-llm-directory" to end of our managed section
    sed -i.tmp '/# para-llm-directory bindings/,/# end para-llm-directory/d' ~/.tmux.conf
    rm -f ~/.tmux.conf.tmp
    # Also remove old-style block (before we added end marker)
    if grep -q "para-llm-directory" ~/.tmux.conf 2>/dev/null; then
        sed -i.tmp '/# para-llm-directory/,/synchronize-panes/d' ~/.tmux.conf
        rm -f ~/.tmux.conf.tmp
    fi
    # Clean up any trailing blank lines
    sed -i.tmp -e :a -e '/^\n*$/{$d;N;ba' -e '}' ~/.tmux.conf 2>/dev/null || true
    rm -f ~/.tmux.conf.tmp
fi

# Add bindings to tmux.conf (always fresh)
echo "Adding bindings pointing to: $SCRIPT_DIR"
cat >> ~/.tmux.conf << EOF

# para-llm-directory bindings
# Ctrl+b c: interactive project + branch selection, creates clone in envs/
bind-key c display-popup -E -w 60% -h 60% "$SCRIPT_DIR/tmux-new-branch.sh"

# Ctrl+b k: cleanup/delete a feature branch environment
bind-key k display-popup -E -w 60% -h 60% "$SCRIPT_DIR/tmux-cleanup-branch.sh"

# Ctrl+b v: Command Center (tiled view of all env windows)
bind-key v run-shell "$SCRIPT_DIR/tmux-command-center.sh"

# Ctrl+b b: Toggle broadcast mode (type in all panes at once)
bind-key b set-window-option synchronize-panes \; display-message "Toggled broadcast mode"

# para-llm-directory: session recovery
set -g @resurrect-dir '$PARA_LLM_ROOT/recovery/resurrect'
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-hook-post-save-all '$PARA_LLM_ROOT/scripts/para-llm-save-state.sh'
set -g @continuum-restore 'off'
set -g @continuum-save-interval '1'
run-shell $PARA_LLM_ROOT/tmux-plugins/tmux-resurrect/resurrect.tmux
run-shell $PARA_LLM_ROOT/tmux-plugins/tmux-continuum/continuum.tmux

# Recovery prompt on tmux start
set-hook -g session-created 'run-shell -b "sleep 1 && $PARA_LLM_ROOT/scripts/para-llm-recovery-prompt.sh"'

# Ctrl+b R: Manual restore trigger
bind-key R run-shell '$PARA_LLM_ROOT/scripts/para-llm-restore.sh'
# end para-llm-directory
EOF
echo "Added bindings to ~/.tmux.conf"

# Reload tmux config if tmux is running
if tmux list-sessions &> /dev/null; then
    tmux source-file ~/.tmux.conf
    echo "Reloaded tmux config - bindings updated in place"
fi

echo ""
echo "Installation complete!"
echo ""
echo "Directory structure:"
echo "  $PARA_LLM_ROOT/"
echo "    envs/          - Feature branch environments"
echo "    recovery/      - Session state + resurrect saves"
echo "    scripts/       - Recovery scripts"
echo "    tmux-plugins/  - tmux-resurrect + tmux-continuum"
echo "    plugins/       - Claude state monitor hooks"
echo ""
echo "Keybindings:"
echo "  Ctrl+b c  - Create/resume feature branch"
echo "  Ctrl+b k  - Cleanup feature branch"
echo "  Ctrl+b v  - Command Center (tiled view of all envs)"
echo "  Ctrl+b b  - Toggle broadcast mode (type in all panes)"
echo "  Ctrl+b R  - Manual restore Claude sessions"
echo ""
echo "Recovery:"
echo "  Sessions auto-saved every 1 minute via tmux-continuum"
echo "  On tmux start: prompted to restore/discard/skip"
echo ""
echo "Optional: Add this alias to your ~/.zshrc or ~/.bashrc:"
echo "  alias envs='$SCRIPT_DIR/envs.sh'"
